[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test = "BCBVVHScphRYjnRqZUa7dZwVZbMY1jJUTQH5WbUTj2PP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
