[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
drvx = "EPjbetVB9ANoNKJCnNFJXRkiSKs7gp7kVKVU2HFJNi4z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
